### ISSUE TITLE
Updating Submodules Confusion

### ISSUE THREAD

**Issue by MrFancyMonocle** [Storj/storj-sdk#4]
Not clear on how to update submodules in this flow for testing; readme instructions not working for checking out. Sometimes after updating a submodule package.json file, NPM install in dockerfile will load a cached value instead, resulting in containers with stale dependencies. Adding the --force flag doesn't seem to correct the issue.

**Comment by retrohacker** [comment]
Heya @MrFancyMonocle,

`git clone --recursive [url]` will grab all of the submodules when first cloning. If this isn't working, can you share results?

For updating to the latest version of a submodule, you'll need to `cd` down into each directory and update. We should def automate this in the future.

For caching the `package.json`, this is weird. `docker build` should notice the hash change and cause a cache miss forcing a rebuild. Are you using `./sdk` or `docker-compose`? Could you share the output of `docker-compose build`?

**Comment by retrohacker** [comment]
`find * -name '.git' | xargs -L1 dirname | xargs -IJ git -C J pull origin master` should update all deps if that helps

**Comment by retrohacker** [comment]
Closing as stale
